# Modify name if deploying multiple instances
name = "sub-box"

main = ".open-next/worker.js"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

minify = true

assets = { directory = ".open-next/assets", binding = "ASSETS" }

# [placement]
# mode = "smart"

# Environment variables
# Modify these to use the correct environment variables
[vars]
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "subbox-admin-Qwer155168" # Change this to a secure password
JWT_SECRET = "EPZN7TaeFQz39FMzA5hL686itni067j6" # Change this to a secure secret key
SESSION_TAG = "0"
SESSION_DURATION = "7d"
DEPLOY_TARGET = "cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "subbox" # Change this to the name of your D1 database
database_id = "e07ea8e7-7688-48b7-bceb-00df7e69a63e" # wrangler d1 info <YOUR_DATABASE_NAME>

[observability.logs]
enabled = true
